# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8096b3c27b52386d215a221e2c517a0320ffaac3e01f32af69a44b2590d31cab7f780fb35e238c6678a26501459e527a4580a0ce3630a81bae97abb74e32d407

test:
  secret_key_base: ed5484ec1c58a4bbcfe83f2d233eff8541d1f4312a70e5b26bbf5ef4441ca416e0e9998ec7e52a284d331484470c6b8fe9f2c730873cbd0ad2e90770433b118d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
